# Generated by Django 4.2.19 on 2025-02-27 00:01

import cvat.apps.engine.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0088_consensus_jobs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="data",
            name="compressed_chunk_type",
            field=models.CharField(
                choices=[
                    ("video", "VIDEO"),
                    ("imageset", "IMAGESET"),
                    ("audio", "AUDIO"),
                    ("list", "LIST"),
                ],
                default=cvat.apps.engine.models.DataChoice["IMAGESET"],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="data",
            name="original_chunk_type",
            field=models.CharField(
                choices=[
                    ("video", "VIDEO"),
                    ("imageset", "IMAGESET"),
                    ("audio", "AUDIO"),
                    ("list", "LIST"),
                ],
                default=cvat.apps.engine.models.DataChoice["IMAGESET"],
                max_length=32,
            ),
        ),
    ]
